apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tasks-app
  labels:
    run: my-tasks-app
spec:
  selector:
    matchLabels:
      run: my-tasks-app
  replicas: 3
  template:
    metadata:
      labels:
        run: my-tasks-app
    spec:
      containers:
        - name: my-tasks-app
          image: shaikezam/task-tracker:1.8
          ports:
            - containerPort: 8090
              #targetPort: 80
              protocol: TCP