FROM alpine:edge
RUN apk add --no-cache openjdk11
RUN apk --no-cache add curl
COPY target/*.jar /app/task-tracker-app.jar
WORKDIR /app
ENTRYPOINT ["java","-Dspring.profiles.active=prod","-jar","task-tracker-app.jar"]