apiVersion: v1
kind: Service
metadata:
  name: my-tasks-app
  labels:
    run: my-tasks-app
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30036
      targetPort: 80
      protocol: TCP
  selector:
    run: my-tasks-app